# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Contact', url: 'contact.html'}
- {name: 'Join', url: 'join.html'}
- {name: 'Publications', url: 'publications.html'}
- {name: 'Research', url: 'research.html'}
- {name: 'Team', url: 'team.html'}



# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/ZenghuPKU'}
- {icon: 'envelope',   link: 'mailto:huzeng@pku.edu.cn}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
